from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

prs = Presentation()
prs.slide_width = Inches(10)
prs.slide_height = Inches(7.5)

def add_slide(layout_type):
    return prs.slides.add_slide(prs.slide_layouts[layout_type])

def set_text_format(text_frame, font_size, bold=False, color=RGBColor(0, 0, 0)):
    for paragraph in text_frame.paragraphs:
        paragraph.font.size = Pt(font_size)
        paragraph.font.bold = bold
        paragraph.font.color.rgb = color
        paragraph.font.name = 'Arial'

slide = add_slide(6)
title_box = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(1))
title_frame = title_box.text_frame
title_frame.text = "FitStep"
title_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
title_frame.paragraphs[0].font.size = Pt(60)
title_frame.paragraphs[0].font.bold = True
title_frame.paragraphs[0].font.color.rgb = RGBColor(17, 17, 17)

subtitle_box = slide.shapes.add_textbox(Inches(1), Inches(3.8), Inches(8), Inches(0.6))
subtitle_frame = subtitle_box.text_frame
subtitle_frame.text = "Fitness Tracking Website"
subtitle_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
subtitle_frame.paragraphs[0].font.size = Pt(32)
subtitle_frame.paragraphs[0].font.color.rgb = RGBColor(107, 91, 82)

subtitle2_box = slide.shapes.add_textbox(Inches(1), Inches(4.6), Inches(8), Inches(0.5))
subtitle2_frame = subtitle2_box.text_frame
subtitle2_frame.text = "Responsive Web Design Project"
subtitle2_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
subtitle2_frame.paragraphs[0].font.size = Pt(24)
subtitle2_frame.paragraphs[0].font.color.rgb = RGBColor(107, 91, 82)

notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "Good morning/afternoon everyone. Today I'm going to present my web development project called FitStep. It's a fitness tracking website that I built using HTML, CSS, and JavaScript. The main focus of my presentation will be on responsive web design and how I made this website work perfectly on mobile, tablet, and desktop devices."

slide = add_slide(1)
title = slide.shapes.title
title.text = "What is FitStep?"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "A complete fitness tracking website"
p = tf.add_paragraph()
p.text = "Helps users monitor their health and fitness"
p.level = 0
p = tf.add_paragraph()
p.text = "Works on all devices (mobile, tablet, desktop)"
p.level = 0
p = tf.add_paragraph()
p.text = "Built with simple web technologies"
p.level = 0
p = tf.add_paragraph()
p.text = "Purpose:"
p.level = 0
p = tf.add_paragraph()
p.text = "Track daily steps and calories"
p.level = 1
p = tf.add_paragraph()
p.text = "Calculate BMI (Body Mass Index)"
p.level = 1
p = tf.add_paragraph()
p.text = "Provide nutrition guidance"
p.level = 1
p = tf.add_paragraph()
p.text = "Offer workout plans and health tips"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(20)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "FitStep is a fitness website I created to help people track their health and fitness activities. The main purpose is to provide users with tools like a step tracker, BMI calculator, and nutrition guides. What makes this project special is that it works perfectly on any device - whether you're using a phone, tablet, or computer. This is called responsive design, which I'll explain more about in the coming slides."

slide = add_slide(1)
title = slide.shapes.title
title.text = "Technologies Used"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "HTML (Structure)"
p = tf.add_paragraph()
p.text = "Created 8 pages"
p.level = 1
p = tf.add_paragraph()
p.text = "Semantic markup"
p.level = 1
p = tf.add_paragraph()
p.text = "Forms and navigation"
p.level = 1
p = tf.add_paragraph()
p.text = "CSS (Styling)"
p.level = 0
p = tf.add_paragraph()
p.text = "Responsive layouts"
p.level = 1
p = tf.add_paragraph()
p.text = "Grid and Flexbox"
p.level = 1
p = tf.add_paragraph()
p.text = "Media queries"
p.level = 1
p = tf.add_paragraph()
p.text = "JavaScript (Functionality)"
p.level = 0
p = tf.add_paragraph()
p.text = "Step tracking"
p.level = 1
p = tf.add_paragraph()
p.text = "BMI calculator"
p.level = 1
p = tf.add_paragraph()
p.text = "Interactive features"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(20)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "I used three main technologies to build this website. First, HTML for creating the structure - I made 8 different pages including home, step tracker, BMI calculator, and more. Second, CSS for styling and making it look good - this is where I implemented responsive design using grids, flexbox, and media queries. Third, JavaScript for adding interactive features like the step tracker that uses your phone's motion sensor and the BMI calculator that does real-time calculations."

slide = add_slide(1)
title = slide.shapes.title
title.text = "Key Features of FitStep"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Step Tracker"
p = tf.add_paragraph()
p.text = "Uses device motion sensor"
p.level = 1
p = tf.add_paragraph()
p.text = "Tracks steps and calories"
p.level = 1
p = tf.add_paragraph()
p.text = "Shows progress bar"
p.level = 1
p = tf.add_paragraph()
p.text = "BMI Calculator"
p.level = 0
p = tf.add_paragraph()
p.text = "Enter height and weight"
p.level = 1
p = tf.add_paragraph()
p.text = "Instant BMI calculation"
p.level = 1
p = tf.add_paragraph()
p.text = "Shows health category"
p.level = 1
p = tf.add_paragraph()
p.text = "Nutrition Guide"
p.level = 0
p = tf.add_paragraph()
p.text = "Healthy food suggestions"
p.level = 1
p = tf.add_paragraph()
p.text = "Meal ideas with images"
p.level = 1
p = tf.add_paragraph()
p.text = "Additional: Workout plans, Health tips, Progress tracking"
p.level = 0
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "FitStep has several key features. The step tracker uses your phone's motion sensor to count steps and calculate calories burned. The BMI calculator lets you enter your height and weight to get instant results. The nutrition guide shows healthy food options with images. I also added pages for workout plans, health tips, and progress tracking. All these features work smoothly on any screen size."

slide = add_slide(1)
title = slide.shapes.title
title.text = "What is Responsive Web Design?"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Definition:"
p = tf.add_paragraph()
p.text = "A website that adapts and looks good on all screen sizes"
p.level = 1
p = tf.add_paragraph()
p.text = "Why is it Important?"
p.level = 0
p = tf.add_paragraph()
p.text = "Mobile Usage"
p.level = 1
p = tf.add_paragraph()
p.text = "60% of web traffic is mobile"
p.level = 2
p = tf.add_paragraph()
p.text = "Users expect mobile-friendly sites"
p.level = 2
p = tf.add_paragraph()
p.text = "Multiple Devices"
p.level = 1
p = tf.add_paragraph()
p.text = "Phones, tablets, laptops, desktops"
p.level = 2
p = tf.add_paragraph()
p.text = "Different screen sizes"
p.level = 2
p = tf.add_paragraph()
p.text = "Better User Experience"
p.level = 1
p = tf.add_paragraph()
p.text = "Easy to read and navigate"
p.level = 2
p = tf.add_paragraph()
p.text = "No zooming or horizontal scrolling"
p.level = 2
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "Responsive web design means creating a website that automatically adjusts to fit any screen size. Whether someone visits your site on a small phone or a large desktop monitor, it should look good and be easy to use. This is extremely important today because more than 60% of internet users browse on mobile devices. If your website doesn't work well on mobile, you'll lose most of your visitors. Responsive design ensures a better user experience - no one has to zoom in or scroll sideways to read content."

slide = add_slide(1)
title = slide.shapes.title
title.text = "How I Made FitStep Responsive"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "1. Media Queries"
p = tf.add_paragraph()
p.text = "@media (max-width: 768px)"
p.level = 1
p = tf.add_paragraph()
p.text = "Different styles for different screens"
p.level = 1
p = tf.add_paragraph()
p.text = "Mobile-first approach"
p.level = 1
p = tf.add_paragraph()
p.text = "2. Flexible Layouts"
p.level = 0
p = tf.add_paragraph()
p.text = "CSS Grid for card layouts"
p.level = 1
p = tf.add_paragraph()
p.text = "Flexbox for navigation"
p.level = 1
p = tf.add_paragraph()
p.text = "Percentage-based widths"
p.level = 1
p = tf.add_paragraph()
p.text = "3. Mobile-Friendly Design"
p.level = 0
p = tf.add_paragraph()
p.text = "Touch-friendly buttons (full-width)"
p.level = 1
p = tf.add_paragraph()
p.text = "Readable font sizes"
p.level = 1
p = tf.add_paragraph()
p.text = "Proper spacing and padding"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "I used three main techniques to make FitStep responsive. First, media queries - these are CSS rules that apply different styles based on screen size. For example, I used 'max-width: 768px' to target mobile devices. Second, flexible layouts using CSS Grid and Flexbox. These modern CSS tools automatically adjust content based on available space. Third, mobile-friendly design principles like making buttons full-width on mobile so they're easy to tap, adjusting font sizes for readability, and adding proper spacing so content doesn't touch the edges of the screen."

slide = add_slide(1)
title = slide.shapes.title
title.text = "Responsive Navigation Bar"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Desktop View:"
p = tf.add_paragraph()
p.text = "Logo on left"
p.level = 1
p = tf.add_paragraph()
p.text = "Navigation links in a row"
p.level = 1
p = tf.add_paragraph()
p.text = "Hover effects"
p.level = 1
p = tf.add_paragraph()
p.text = "Mobile View:"
p.level = 0
p = tf.add_paragraph()
p.text = "Hamburger menu (☰)"
p.level = 1
p = tf.add_paragraph()
p.text = "Links hidden by default"
p.level = 1
p = tf.add_paragraph()
p.text = "Vertical dropdown when clicked"
p.level = 1
p = tf.add_paragraph()
p.text = "Implementation:"
p.level = 0
p = tf.add_paragraph()
p.text = "Display: flex for desktop"
p.level = 1
p = tf.add_paragraph()
p.text = "Display: none for mobile links"
p.level = 1
p = tf.add_paragraph()
p.text = "JavaScript toggle for menu"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "The navigation bar is one of the most important responsive elements. On desktop, you see the logo on the left and all navigation links in a horizontal row. But on mobile, there's not enough space for all those links. So I implemented a hamburger menu - that's the three-line icon you see on mobile sites. When you click it, the menu slides down and shows all links vertically. This is done using CSS to hide the links by default on mobile, and JavaScript to toggle them open and closed when the hamburger icon is clicked."

slide = add_slide(1)
title = slide.shapes.title
title.text = "Responsive Grid Layouts"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Desktop Layout:"
p = tf.add_paragraph()
p.text = "Feature cards: 3 columns"
p.level = 1
p = tf.add_paragraph()
p.text = "Nutrition cards: 4 columns"
p.level = 1
p = tf.add_paragraph()
p.text = "Stats cards: 3 columns"
p.level = 1
p = tf.add_paragraph()
p.text = "Tablet Layout:"
p.level = 0
p = tf.add_paragraph()
p.text = "Feature cards: 2 columns"
p.level = 1
p = tf.add_paragraph()
p.text = "Nutrition cards: 2 columns"
p.level = 1
p = tf.add_paragraph()
p.text = "Stats cards: 3 columns"
p.level = 1
p = tf.add_paragraph()
p.text = "Mobile Layout:"
p.level = 0
p = tf.add_paragraph()
p.text = "All cards: 1 column (stacked)"
p.level = 1
p = tf.add_paragraph()
p.text = "Full-width design"
p.level = 1
p = tf.add_paragraph()
p.text = "Easy scrolling"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "The layout changes dramatically based on screen size. On desktop, I show feature cards in 3 columns, nutrition cards in 4 columns, and stats in 3 columns. On tablets, this reduces to 2 or 3 columns. On mobile phones, everything stacks into a single column for easy scrolling. I achieved this using CSS Grid with the 'grid-template-columns' property. On mobile, I use '1fr' which means one column taking full width. On desktop, I use 'repeat(3, 1fr)' which creates three equal columns. This makes the content adapt beautifully to any screen size."

slide = add_slide(1)
title = slide.shapes.title
title.text = "Mobile-Specific Optimizations"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Typography:"
p = tf.add_paragraph()
p.text = "Heading: 2.5rem → 1.8rem"
p.level = 1
p = tf.add_paragraph()
p.text = "Body text: 1.1rem → 1rem"
p.level = 1
p = tf.add_paragraph()
p.text = "Readable on small screens"
p.level = 1
p = tf.add_paragraph()
p.text = "Buttons:"
p.level = 0
p = tf.add_paragraph()
p.text = "Desktop: Normal width"
p.level = 1
p = tf.add_paragraph()
p.text = "Mobile: Full-width (100%)"
p.level = 1
p = tf.add_paragraph()
p.text = "Easy to tap (min 44px height)"
p.level = 1
p = tf.add_paragraph()
p.text = "Spacing:"
p.level = 0
p = tf.add_paragraph()
p.text = "Reduced padding on mobile"
p.level = 1
p = tf.add_paragraph()
p.text = "Content doesn't touch edges"
p.level = 1
p = tf.add_paragraph()
p.text = "Images: max-width: 100%, height: auto"
p.level = 0
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "I made several specific optimizations for mobile devices. First, typography - I reduced heading sizes from 2.5rem to 1.8rem on mobile so they don't take up too much space. Second, buttons become full-width on mobile, making them much easier to tap with your finger. I also ensured buttons are at least 44 pixels tall, which is the recommended minimum touch target size. Third, spacing - I reduced padding on mobile to maximize screen space while ensuring content doesn't touch the edges. Finally, all images are set to scale properly using 'max-width: 100%' and 'height: auto', so they never overflow the screen."

slide = add_slide(1)
title = slide.shapes.title
title.text = "Challenges & Solutions"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Challenge 1: Navbar Overflow"
p = tf.add_paragraph()
p.text = "Problem: Too many links on mobile"
p.level = 1
p = tf.add_paragraph()
p.text = "Solution: Hamburger menu with toggle"
p.level = 1
p = tf.add_paragraph()
p.text = "Challenge 2: Layout Breaking"
p.level = 0
p = tf.add_paragraph()
p.text = "Problem: Cards looked bad on tablets"
p.level = 1
p = tf.add_paragraph()
p.text = "Solution: Added tablet breakpoint (768px)"
p.level = 1
p = tf.add_paragraph()
p.text = "Challenge 3: Mobile View Issues"
p.level = 0
p = tf.add_paragraph()
p.text = "Problem: Content touching screen edges"
p.level = 1
p = tf.add_paragraph()
p.text = "Solution: Added proper padding (1rem)"
p.level = 1
p = tf.add_paragraph()
p.text = "What I Learned:"
p.level = 0
p = tf.add_paragraph()
p.text = "Test on multiple devices"
p.level = 1
p = tf.add_paragraph()
p.text = "Mobile-first approach is better"
p.level = 1
p = tf.add_paragraph()
p.text = "Small details matter"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(16)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "I faced several challenges while making FitStep responsive. The first challenge was navbar overflow - I had 8 navigation links that looked fine on desktop but were cramped on mobile. I solved this by implementing a hamburger menu. The second challenge was that my layout looked perfect on mobile and desktop but broke on tablets. I fixed this by adding a specific breakpoint at 768 pixels for tablet devices. Third, on mobile, my content was touching the screen edges, which looked unprofessional. I added proper padding of 1rem on all sides. Through these challenges, I learned the importance of testing on multiple devices and that small details really matter in responsive design."

slide = add_slide(1)
title = slide.shapes.title
title.text = "What I Learned"
content = slide.placeholders[1]
tf = content.text_frame
tf.text = "Technical Skills:"
p = tf.add_paragraph()
p.text = "HTML structure and semantic markup"
p.level = 1
p = tf.add_paragraph()
p.text = "CSS Grid and Flexbox layouts"
p.level = 1
p = tf.add_paragraph()
p.text = "Media queries for responsiveness"
p.level = 1
p = tf.add_paragraph()
p.text = "JavaScript for interactivity"
p.level = 1
p = tf.add_paragraph()
p.text = "Design Principles:"
p.level = 0
p = tf.add_paragraph()
p.text = "Mobile-first approach"
p.level = 1
p = tf.add_paragraph()
p.text = "User experience matters"
p.level = 1
p = tf.add_paragraph()
p.text = "Testing is essential"
p.level = 1
p = tf.add_paragraph()
p.text = "Key Takeaway:"
p.level = 0
p = tf.add_paragraph()
p.text = "Responsive design is not optional - it's essential for modern websites"
p.level = 1
for paragraph in tf.paragraphs:
    paragraph.font.size = Pt(18)
    paragraph.font.name = 'Arial'
notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "Working on this project taught me a lot. Technically, I learned how to structure HTML properly, use CSS Grid and Flexbox for layouts, implement media queries for responsiveness, and add interactivity with JavaScript. Beyond technical skills, I learned important design principles - that mobile-first approach is better, user experience should be the top priority, and thorough testing is essential. My key takeaway is that responsive design is not optional anymore - it's absolutely essential for any modern website."

slide = add_slide(6)
thank_box = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(1))
thank_frame = thank_box.text_frame
thank_frame.text = "Thank You!"
thank_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
thank_frame.paragraphs[0].font.size = Pt(54)
thank_frame.paragraphs[0].font.bold = True
thank_frame.paragraphs[0].font.color.rgb = RGBColor(17, 17, 17)

question_box = slide.shapes.add_textbox(Inches(1), Inches(3.8), Inches(8), Inches(0.6))
question_frame = question_box.text_frame
question_frame.text = "Questions?"
question_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
question_frame.paragraphs[0].font.size = Pt(32)
question_frame.paragraphs[0].font.color.rgb = RGBColor(107, 91, 82)

project_box = slide.shapes.add_textbox(Inches(1), Inches(5), Inches(8), Inches(0.8))
project_frame = project_box.text_frame
project_frame.text = "FitStep Project\nResponsive Web Design"
project_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
project_frame.paragraphs[0].font.size = Pt(20)
project_frame.paragraphs[0].font.color.rgb = RGBColor(107, 91, 82)
project_frame.paragraphs[1].alignment = PP_ALIGN.CENTER
project_frame.paragraphs[1].font.size = Pt(20)
project_frame.paragraphs[1].font.color.rgb = RGBColor(107, 91, 82)

notes_slide = slide.notes_slide
notes_slide.notes_text_frame.text = "Thank you for your attention. I hope this presentation gave you a good understanding of responsive web design and how I implemented it in my FitStep project. I'm happy to answer any questions you might have about the project, the code, or responsive design in general."

prs.save('FitStep_Presentation.pptx')
